site_name: bibliography
site_url: https://goessl.github.io/bibliography/
site_author: Sebastian Gössl
site_description: Physics bibliography.

repo_name: goessl/bibliography
repo_url: https://github.com/goessl/bibliography

copyright: Copyright &copy; 2026 Sebastian Gössl

theme:
  name: material
  features:
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/goessl/
      name: goessl on Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/lordgoessl/
      name: lordgoessl on Instagram

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

hooks:
  - gen.py

extra_css:
  - https://unpkg.com/tabulator-tables/dist/css/tabulator_simple.min.css
  - stylesheets/bibliography.css

extra_javascript:
  - https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js
  - javascripts/bibliography.js

nav:
  - Home: index.md
  - bibliography.md
